Add blogpost on Signalen's incubation
publiccodenet/blog pull request #150
Opened 2021-02-04 09:30 UTC by Ainali

Fixes #149

2021-02-04 09:42 UTC, felixfaassen requested changes
I think it is important to clarify what incubation means and how this relates to the commitment VNG has made of doing taking the lead in doing the stewarding work. Essentially they decided the VNG realisatie will commit to lead the community building and stewarding efforts in scaling up signalen. In order not to confuse people in the community and the people we work with at VNG I think we should add the position of VNG and how we help them with that effort.

2021-02-04 09:46 UTC, ElenaFdR commented
@felixfaassen Is this explained publicly anywhere that we can link to, or would our blogpost also be the first English explanation of the VNG/VNG-R in the Dutch codebase ecosystem?

2021-02-04 10:00 UTC, felixfaassen commented
B

> @felixfaassen Is this explained publicly anywhere that we can link to, or would our blogpost also be the first English explanation of the VNG/VNG-R's role in the Dutch codebase ecosystem?

@ElenaFdR @Ainali not yet as they are using the Signalen project as a try-out but Jacco is communicating it to the community.

2021-02-04 13:44 UTC, Ainali commented
I and Felix had a chat, and the blog post as it is works, since it is very clear on what incubation in this specific case means. Bearing that in mind, it's important that the language used when promoting the blog post also is clear about it is incubation for the Standard for Public Code we are referring to.

2021-02-08 16:19 UTC, felixfaassen approved these changes

2021-02-11 13:24 UTC, ElenaFdR commented on _posts/2021-02-04-signalen-is-in-incubation.md
> +This is an important milestone in the Signalen community's ambition, reflecting their strong commitment to openness and collaboration.
```suggestion
This is an important milestone in the Signalen community's ambitions, reflecting their strong commitment to openness and collaboration.
```

2021-02-11 13:25 UTC, ElenaFdR commented on _posts/2021-02-04-signalen-is-in-incubation.md
> +* [See the other codebases we work with](https://publiccode.net/codebases/).
```suggestion
* [See the other codebases we work with](https://publiccode.net/codebases/)
```

2021-02-11 13:34 UTC, ElenaFdR approved these changes
Ready to go!

2021-02-11 13:35 UTC, merged