Winter 20/21 newsletter
publiccodenet/blog pull request #165
Opened 2021-03-04 14:08 UTC by ElenaFdR

This will be ready for review when the mailing list version is ready, to ensure that any changes are made to both versions in parallel.

2021-03-04 15:27 UTC, Ainali approved these changes
Yay! More news to the world!

2021-03-05 08:51 UTC, felixfaassen commented
The reason why this is failing is not the fault of travis:

- ./_site/news/2021/03/04/newsletter-dec-2020-to-feb-2021.html

  *  internally linking to https//:schedule.mozillafestival.org/session/TDHQ3D-1, which does not exist (line 114)

     <a href="https//:schedule.mozillafestival.org/session/TDHQ3D-1">register here</a>


The URI is spelled incorrectly: **https//:**schedule.mozillafestival.org/session/TDHQ3D-1

it should be **https://**

2021-03-05 08:54 UTC, felixfaassen requested changes

2021-03-05 08:54 UTC, felixfaassen commented on _posts/2021-03-04-newsletter-dec-2020-to-feb-2021.md
> +- MozFest 2021: come discuss "How public code can transform the digital future of cities" with our President Ben Cerveny and Ger Baron, CTO of Amsterdam on March 11th at 19:15 [register here](https//
URI misspelled - change to **https://*

2021-03-05 10:48 UTC, ElenaFdR commented on _posts/2021-03-04-newsletter-dec-2020-to-feb-2021.md
> +- MozFest 2021: come discuss "How public code can transform the digital future of cities" with our President Ben Cerveny and Ger Baron, CTO of Amsterdam on March 11th at 19:15 [register here](https//
Amazing spot, thank you!

2021-03-05 10:55 UTC, felixfaassen approved these changes
GREAT!

2021-03-05 11:42 UTC, merged